spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.136.201.226:1433;DatabaseName=bigHomework
    username: sa
    password: wtbnb
server:
  port: 8443