spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.43.139:1433;DatabaseName=bigHomework
    username: sa
    password: wtbnb
server:
  port: 8443